### ISSUE TITLE
Get rid of boilerplate-server, join patternplate projects

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/patternplate#102]
## Rationale

The current separation of patternplate into `patternplate-client` and `patternplate-server` does not serve any real purpose and introduces considerable overhead. Additionally the `boilerplate-server` dependency with its convention over configuration mechanisms introduces complexity and yields less benefits than expected. 
## ToDo
- [ ] Remove dependency on `boilerplate-server` from `patternplate-client`
- [ ] Remove dependency on `boilerplate-server` from `patternplate-server`
- [ ] Remove dependency on `boilerplate-server` from `patternplate`
- [ ] Move `patternplate-client` to `patternplate` repository 
- [ ] Move `patternplate-server` to `patternplate` repository
- [ ] Add notices about the move on the `patternplate-{client,server}` repositories
- [ ] Discontinue the `patternplate-{client,server}` packages
- [ ] Deprecate `boilerplate-server`, add discontinuation notice to repository

**Comment by marionebl** [comment]
This will be implemented via `2.0`
