### ISSUE TITLE
Feature Request: Theming for PP-Client

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate#141]
Some users may want to theme the patternplate as part of their brand guide. Therefore we could provide a way to make the patternplate colors configurable.

In short: Everything that currently is "blueish" could be any color. 

These colors could be configured in patternplate-client config.

**Comment by SaraVieira** [comment]
I was in this situation, I wanted to add some of the company's branding but it was impossible without forking the client.
The main points that I think should be changeable would be the logo, the name that shows up beside the logo and the main colors, mainly the blue and dark gray.

Maybe adding a custom-ui.less would be too much since the user could then change anything and patternplate would loose the brand but a config.js on the client config I don't think would be a bad idea something like this:

```
{
 title: "My Awesome UI",
 logo: "path/to/logo.svg"
 mainColor: '#BADA55', // The main gray
 accentColor: '#FB1' // The blue
}

Probably just this object would be more than enough for most people

/cc @marionebl @KnisterPeter @LKuechler @Dangoo

**Comment by Dangoo** [comment]
Hey @SaraVieira ,

thanks for your input! This is what I thought too, but maybe just the highlight colors should be configurable like this:

configuration/patternplate-client/ui.js
```js
{
  title: "My Awesome Patternplate",
  logo: "path/to/logo.svg"
  uiColors: {
    mainColor:  '#BADA55', // A badass companys green
    mainHighlightColor: '#DEC0DE' // Highlight color for hover etc.
  }
}
```

To let a user manipulate the background colors would require to make colors for borders, shadows etc. configurable too.

**Comment by SaraVieira** [comment]
That is true too, It would be a lot of work that most people wouldn't need, and grey goes with everything :)

I completely agree with your idea @Dangoo , if you later need help implementing this I would love to help 👍

**Comment by marionebl** [comment]
I am a bit concerned with the amount of effort this needs - basically the current styling system has to be replaced entirely.

Options to do this that come to my mind:

1. Compiling `less` to `css` on request, feed some options object into less to replace given vars
2. Switch to css via js approach, e.g. [styled-components](https://github.com/styled-components/styled-components)

Currently I favor option 2 as it makes our intent on having configurable styling way clearer.

**Comment by marionebl** [comment]
> Most of the color nuances is solved by opacity anyways :)

@Dangoo I think a lot of CI guidelines impose very specific rules on colors usage, often banning/regulating the usage of desaturation/opacity/shades explicitly. Not entirely sure on this but I feel we'd have to change the current opacity/shades system to a more explicit one that allows the user to control each of the current highlight color variations separately.

**Comment by marionebl** [comment]
> The main points that I think should be changeable would be the logo, the name that shows up beside the logo and the main colors, mainly the blue and dark gray.

@SaraVieira Changing the title and logo is already possible (lacking documentation though, sorry for that):

1. **Changing the title (compare [patternplate-ui](https://github.com/sinnerschrader/patternplate-ui/blob/master/configuration/patternplate-client/ui.js))**

```js
// in configuration/patternplate-client/ui.js
module.exports = {
  title: 'Other title' // overrides package.json name field used by default
};
```

2. **Changing the logo** 
```js
// in configuration/patternplate-client/ui.js
module.exports = {
  logo: '<svg viewBox="0 0 24 24"><rect width="24" height="24" fill="red"/></svg>'
};
```

**Comment by SaraVieira** [comment]
Oh ! Awesome then , I'll try that this afternoon 👍 

Those are the only two options in ui.js right ?

**Comment by marionebl** [comment]
@SaraVieira There are a bunch of others, see #143 for more info on this.

**Comment by Dangoo** [comment]
> I think a lot of CI guidelines impose very specific rules on colors usage, often banning/regulating the usage of desaturation/opacity/shades explicitly. Not entirely sure on this but I feel we'd have to change the current opacity/shades system to a more explicit one that allows the user to control each of the current highlight color variations separately.

Giving users the ability to theme the UI is a nice thing but comes with a very high price on the development side compared to the gain of it. Additionally it is not a core feature of any kind so we should not invest too much effort in this. So I'd start with the **color variations based on one (brand) color**. In the future one could think about complete custom styles…  🤔

Another constraint we have to keep in mind is that we can't know if someone uses a color that is too close to either the bright or the dark themes background-color. This customization might increase complexity of future interface changes.

> 1. Compiling less to css on request, feed some options object into less to replace given vars

I already started to dig into this and managed to insert a custom color via parameters to npm script `build:styles`. The problem here is: When do we want to build the styles? Is it:
* only on install in patternplate
* each time starting the patternplate

Option 1 is usable with the current styling architecture but on the other hand side less intuitive to use.
Option 2 feels way too heavy to perform on each start action.

@marionebl Is it possible to pass options from `configuration/patternplate-client/ui.js` to patternplate-client while `post-install`?

**Comment by marionebl** [comment]
> Additionally it is not a core feature of any kind so we should not invest too much effort in this. 

I beg to differ - most projects catering strict CI guidelines would benefit from this. There is a notable cost for any web-interface that is not compliant with the relevant rules, most likely paid in customers/teams not using the interface as way to spread knowledge in their org.

> So I'd start with the color variations based on one (brand) color. In the future one could think about complete custom styles…  🤔

Totally okay with prototyping this via the highlight color only. To be clear: I do not intend a full costum styling API, just making all highlight-derived colors in the interface customizable via overridable variables.

> Another constraint we have to keep in mind is that we can't know if someone uses a color that is too close to either the bright or the dark themes background-color. This customization might increase complexity of future interface changes.

I'd classify such things as user-land problem we can safely ignore. The backwards-compat bit is something to think about, though.

> I already started to dig into this and managed to insert a custom color via parameters to npm script build:styles. The problem here is: When do we want to build the styles? Is it:

> - only on install in patternplate
> - each time starting the patternplate

> Option 1 is usable with the current styling architecture but on the other hand side less intuitive to use.
> Option 2 feels way too heavy to perform on each start action.
> @marionebl Is it possible to pass options from configuration/patternplate-client/ui.js to patternplate-client while post-install?

I'd refrain from adding a post-install script to `patternplate-client` to  keep the install complexity as low as possible. What we could do instead:

- Compile less async as soon as patternplate starts
- Hash current ui settings, use as filename for result css
- When request for css hit the server
   - Hashed filename in cache: Deliver
   - Not in cache: Wait for compilation, deliver

**Comment by SaraVieira** [comment]
@marionebl The logo and title worked like a charm. Thanks

**Comment by Dangoo** [comment]
So I resume:

## Tasks
- [ ] Make highlight colors and their subsets configurable in LESS
- [ ] Add async build-task for CSS on patternplate start (Hash from config as identifier)
- [ ] Integrate async loading of CSS

## Open Questions
* How many steps should we provide for each color? (Proposal: 3)
Currently we're using three color steps:
  * **Main color**
    * clickable / links
    * active items
  * **Main color 0.5**
    * hover
    * active items 2nd level
  * **Main color 0.15**
    * menu item hover
    * folder content table hover
* Should the main background-colors for bright/dark theme be configurable too? (Proposal: yes)
Allows some adjustments towards brand guidelines "50 shades of grey…"
